(function(){
  window.ECHO_GARDEN_CONFIG = {
    app: {
      sourceOfTruth: 'index.html',
      version: '0.1.0',
      compositionBaselineSize: { w: 1280, h: 720 },
      defaultPrintDpi: 300,
      appMode: 'public',
    },
    commerce: {
      shopifyHandoffTargetUrl: 'https://echo-garden-stg.myshopify.com/',
      shopifyHandoffQueryParam: 'artwork_id',
      includeSerialCodeInShopifyHandoff: false,
    },
    stateDefaults: {
      gW: 2048,
      gH: 1152,
      bgHex: '#04070b',
      aspectBucketId: 'landscape',
      captureIntervalMs: 5000,
    },
    featureSets: {
      full: {
        enable_recording: false,
        enable_auto_capture: false,
        enable_high_res_export: false,
        enable_advanced_scenes: true,
        enable_mixed_mode: true,
        enable_metadata_export: true,
        enable_export_presets: true,
        enable_transparent_export: true,
        enable_guided_mode: true,
        enable_public_audio_controls: false,
        enable_public_visual_controls: false,
        enable_public_direct_export_controls: false,
      },
      public: {
        enable_recording: false,
        enable_auto_capture: false,
        enable_high_res_export: false,
        enable_advanced_scenes: true,
        enable_mixed_mode: true,
        enable_metadata_export: true,
        enable_export_presets: true,
        enable_transparent_export: false,
        enable_guided_mode: false,
        enable_public_audio_controls: false,
        enable_public_visual_controls: false,
        enable_public_direct_export_controls: false,
      },
    },
    exportPresets: {
      social_1280x720: {
        id: 'social_1280x720',
        label: 'social 1280 x 720',
        width: 1280,
        height: 720,
        w: 1280,
        h: 720,
        category: 'social',
        intendedUse: 'social sharing',
        targetDpi: null,
        transparentBackgroundAllowed: false,
      },
      social_1920x1080: {
        id: 'social_1920x1080',
        label: 'social 1920 x 1080',
        width: 1920,
        height: 1080,
        w: 1920,
        h: 1080,
        category: 'social',
        intendedUse: 'social sharing',
        targetDpi: null,
        transparentBackgroundAllowed: false,
      },
      share_landscape_2048x1152: {
        id: 'share_landscape_2048x1152',
        label: 'share landscape 2048 x 1152',
        width: 2048,
        height: 1152,
        w: 2048,
        h: 1152,
        category: 'share',
        intendedUse: 'share landscape',
        targetDpi: null,
        transparentBackgroundAllowed: false,
      },
      share_portrait_1152x2048: {
        id: 'share_portrait_1152x2048',
        label: 'share portrait 1152 x 2048',
        width: 1152,
        height: 2048,
        w: 1152,
        h: 2048,
        category: 'share',
        intendedUse: 'share portrait',
        targetDpi: null,
        transparentBackgroundAllowed: false,
      },
      share_square_2048x2048: {
        id: 'share_square_2048x2048',
        label: 'share square 2048 x 2048',
        width: 2048,
        height: 2048,
        w: 2048,
        h: 2048,
        category: 'share',
        intendedUse: 'share square',
        targetDpi: null,
        transparentBackgroundAllowed: false,
      },
      print_square_3000x3000: {
        id: 'print_square_3000x3000',
        label: 'print square 3000 x 3000',
        width: 3000,
        height: 3000,
        w: 3000,
        h: 3000,
        category: 'print',
        intendedUse: 'square print / merch',
        printWidthInches: 10,
        printHeightInches: 10,
        targetDpi: 300,
        transparentBackgroundAllowed: false,
      },
      print_dtg_front_3600x4800: {
        id: 'print_dtg_front_3600x4800',
        label: 'DTG front 3600 x 4800',
        width: 3600,
        height: 4800,
        w: 3600,
        h: 4800,
        category: 'print',
        intendedUse: 'dtg front print',
        printWidthInches: 12,
        printHeightInches: 16,
        targetDpi: 300,
        transparentBackgroundAllowed: false,
      },
      print_poster_a4_2480x3508: {
        id: 'print_poster_a4_2480x3508',
        label: 'A4 poster 2480 x 3508',
        width: 2480,
        height: 3508,
        w: 2480,
        h: 3508,
        category: 'print',
        intendedUse: 'A4 poster',
        printWidthMm: 210,
        printHeightMm: 297,
        targetDpi: 300,
        transparentBackgroundAllowed: false,
      },
    },
    guidedDefaults: {
      enabled: false,
      targetImage: null,
      targetImageMeta: null,
      targetStyle: null,
      stylePreset: null,
      audioInfluence: 1.0,
      styleInfluence: 0.0,
      guidanceStrength: 0.0,
      targetFitMode: 'contain',
      targetOpacity: 0.0,
    },
    uiDefaults: {
      gain: 2.6,
      smooth: 0.5,
      fft: 1024,
      pitchMode: 'cont',
      key: 'A',
      colorMode: 'pitch',
      trail: 0.0,
      particles: 600,
      bgColor: '#04070b',
      spawnMode: 'randomized',
      micGain: 1.0,
    },
    publicPresetConfig: {
      publicDefaults: {
        renderPresetId: 'public_default',
        modePresetId: 'balanced_garden',
        aspectBucketId: 'landscape',
        deviceProfileId: 'standard',
        exportProfileId: 'share_landscape',
      },
      renderPresets: {
        public_default: {
          audio: { gain: 2.6, smooth: 0.5, fft: 1024 },
          pitch: { mode: 'cont', key: 'A' },
          visual: {
            colorMode: 'pitch',
            trail: 0.0,
            particles: 600,
            bgColor: '#04070b',
            spawnMode: 'randomized',
          },
        },
      },
      modePresets: {
        balanced_garden: {
          activeScenes: ['autobrush', 'fireworks', 'flower', 'particles', 'ink'],
          defaultRenderPresetId: 'public_default',
          spawnMode: 'randomized',
        },
      },
      aspectBuckets: {
        landscape: {
          label: '横長',
          width: 2048,
          height: 1152,
          exportProfileId: 'share_landscape',
          metadataValue: 'landscape',
        },
        portrait: {
          label: '縦長',
          width: 1152,
          height: 2048,
          exportProfileId: 'share_portrait',
          metadataValue: 'portrait',
        },
        square: {
          label: '正方形',
          width: 2048,
          height: 2048,
          exportProfileId: 'share_square',
          metadataValue: 'square',
        },
      },
      deviceProfiles: {
        standard: {
          audio: { micGain: 1.0 },
          limits: {
            maxParticles: 800,
            maxCanvasPixels: 4194304,
          },
          performance: { targetFrameRate: 60 },
        },
      },
      exportProfiles: {
        share_landscape: {
          exportPresetId: 'share_landscape_2048x1152',
          intendedUse: 'share',
          requiresMetadata: true,
          requiresUpload: false,
          transparentBackground: false,
        },
        share_portrait: {
          exportPresetId: 'share_portrait_1152x2048',
          intendedUse: 'share',
          requiresMetadata: true,
          requiresUpload: false,
          transparentBackground: false,
        },
        share_square: {
          exportPresetId: 'share_square_2048x2048',
          intendedUse: 'share',
          requiresMetadata: true,
          requiresUpload: false,
          transparentBackground: false,
        },
      },
    },
    canvasPresets: [
      { id: 'social_1920x1080', width: 1920, height: 1080, label: '1920 x 1080 横(16:9)' },
      { id: 'social_1280x720', width: 1280, height: 720, label: '1280 x 720 横(軽量)' },
      { id: 'portrait_720x1280', width: 720, height: 1280, label: '720 x 1280 縦(9:16軽量)' },
      { id: 'portrait_1080x1920', width: 1080, height: 1920, label: '1080 x 1920 縦(9:16)' },
      { id: 'poster_1350x1920', width: 1350, height: 1920, label: '1350 x 1920 縦(ポスター)' },
      { id: 'square_1080x1080', width: 1080, height: 1080, label: '1080 x 1080 正方形' },
      { id: 'square_2048x2048', width: 2048, height: 2048, label: '2048 x 2048 正方形(高解像度)' },
    ],
  };
})();
